// Define your own mock data here:
export const standard = () => ({
  jubens: [
    {
      id: 1,
      name: '作者不详',
      score: 4.9,
      sections: '日式 惊悚 推理 变革 还原',
      players: '0|6',
      image: 'https://cdn.filestackcontent.com/Wr5vCCfuQ1eOd1pK95FF',
    },
    {
      id: 2,
      name: '死者在幻夜中醒来',
      score: 4.9,
      sections: '日式 惊悚 推理 变革 硬核',
      players: '4|3',
      image: 'https://cdn.filestackcontent.com/uNBHpifLR3OpSjnp7Kln',
    },
    {
      id: 3,
      name: '漓川怪谈薄',
      score: 4.9,
      sections: '日式 推理 进阶',
      players: '3|4',
      image: 'https://cdn.filestackcontent.com/R0rPfWX6SKuXO4nEQ2oy',
    },
    {
      id: 4,
      name: '神乐汤',
      score: 4.8,
      sections: '日式 机制 本格 进阶',
      players: '3|2',
      image: 'https://cdn.filestackcontent.com/RKaxGI3TG1niRirP9rJQ',
    },
    {
      id: 5,
      name: '青楼2',
      score: 4.9,
      sections: '古风 阵营 机制 进阶',
      players: '4|3',
      image: 'https://cdn.filestackcontent.com/fore5xbHRJWmC0fagCvp',
    },
    {
      id: 6,
      name: '病娇男孩的精分日记',
      score: 4.9,
      sections: '现代 惊悚 硬核 推理',
      players: '7|0',
      image: 'https://cdn.filestackcontent.com/oOcvLTYQPnes2zOwlUxg',
    },
    {
      id: 7,
      name: '市井狂人',
      score: 5,
      sections: '现代 欢乐 机制 新手',
      players: '5|2',
      image: 'https://cdn.filestackcontent.com/VFBxYALQIyV2xD2RWCmA',
    },
    {
      id: 8,
      name: '再见萤火虫',
      score: 4.9,
      sections: '日式 情感 开放 进阶',
      players: '4|3',
      image: 'https://cdn.filestackcontent.com/eyzDDfJVTiyqzpF4yjwq',
    },
    {
      id: 9,
      name: '古木吟',
      score: 4.9,
      sections: '现代 情感 进阶',
      players: '3|3',
      image: 'https://cdn.filestackcontent.com/0GfhqqBnQRGuJxxqsfSp',
    },
    {
      id: 10,
      name: '那一束月光',
      score: 4.9,
      sections: '现代 欢乐 机制 新手',
      players: '3|3',
      image: 'https://cdn.filestackcontent.com/RDmVX3oYTa2o7b36WQwA',
    },
  ],
})
