-- AlterTable
ALTER TABLE "User" ADD COLUMN "desc" TEXT;
ALTER TABLE "User" ADD COLUMN "gaoxiao" REAL;
ALTER TABLE "User" ADD COLUMN "knot" TEXT;
ALTER TABLE "User" ADD COLUMN "label" TEXT;
ALTER TABLE "User" ADD COLUMN "qinggan" REAL;
ALTER TABLE "User" ADD COLUMN "thumbnail" TEXT;
ALTER TABLE "User" ADD COLUMN "tuili" REAL;
ALTER TABLE "User" ADD COLUMN "xiezuo" REAL;
ALTER TABLE "User" ADD COLUMN "yanji" REAL;
